### ISSUE TITLE
Failed to build the project while i followed the official guides.

### ISSUE THREAD

**Issue by a347807131** [nroduit/weasis-i18n#1]
I cloned it and lunch cmd at `clean install -Dtransifex.token=********************`
then

> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.weasis.maven:build-xz-plugin:1.1.0:packFiles (xz) on project weasis-core-i18n: Execution xz of goal org.weasis.maven:build-xz-plugin:1.1.0:packFiles failed: A required class was missing while executing org.weasis.maven:build-xz-plugin:1.1.0:packFiles: org/codehaus/plexus/util/StringUtils
> [ERROR] -----------------------------------------------------
> [ERROR] realm =    plugin>org.weasis.maven:build-xz-plugin:1.1.0
> [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
> [ERROR] urls[0] = file:/workspace/m2-repository/org/weasis/maven/build-xz-plugin/1.1.0/build-xz-plugin-1.1.0.jar
> [ERROR] urls[1] = file:/workspace/m2-repository/org/tukaani/xz/1.9/xz-1.9.jar
> [ERROR] Number of foreign imports: 1
> [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
> [ERROR] 
> [ERROR] -----------------------------------------------------
> [ERROR] : org.codehaus.plexus.util.StringUtils
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

i appriciate any help, thanks.

**Comment by nroduit** [comment]
It seems to be related to [Maven 3.9.0 breaking change](https://stackoverflow.com/questions/75652635/a-required-class-was-missing-while-executing-maven-plugin-with-github-action). I publish a fix.
